!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_qutraj_run_getdims_tlist(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => tlist

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_tlist
      subroutine f2py_qutraj_run_getdims_psi0(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => psi0

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_psi0
      subroutine f2py_qutraj_run_getdims_sol(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => sol

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1),s(2),s(3),s(4)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_sol
      subroutine f2py_qutraj_run_getdims_csr_val(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => csr_val

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_csr_val
      subroutine f2py_qutraj_run_getdims_csr_col(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => csr_col

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_csr_col
      subroutine f2py_qutraj_run_getdims_csr_ptr(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => csr_ptr

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_csr_ptr
      subroutine f2py_qutraj_run_getdims_col_times(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => col_times

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_col_times
      subroutine f2py_qutraj_run_getdims_col_which(r,s,f2pysetdata,flag)
      use qutraj_run, only: d => col_which

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_col_which
      subroutine f2py_qutraj_run_getdims_psi0_dims1(r,s,f2pysetdata,flag&
     &)
      use qutraj_run, only: d => psi0_dims1

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_psi0_dims1
      subroutine f2py_qutraj_run_getdims_ptrace_sel(r,s,f2pysetdata,flag&
     &)
      use qutraj_run, only: d => ptrace_sel

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_ptrace_sel
      subroutine f2py_qutraj_run_getdims_reduced_state_entropy(r,s,f2pys&
     &etdata,flag)
      use qutraj_run, only: d => reduced_state_entropy

      integer flag
      external f2pysetdata
      logical ns
      integer r,i
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_qutraj_run_getdims_reduced_state_entropy
      
      subroutine f2pyinitqutraj_run(f2pysetupfunc)
      use qutraj_run, only : ntraj
      use qutraj_run, only : n_e_ops
      use qutraj_run, only : n_c_ops
      use qutraj_run, only : unravel_type
      use qutraj_run, only : average_states
      use qutraj_run, only : average_expect
      use qutraj_run, only : tlist
      use qutraj_run, only : order
      use qutraj_run, only : nsteps
      use qutraj_run, only : first_step
      use qutraj_run, only : min_step
      use qutraj_run, only : max_step
      use qutraj_run, only : psi0
      use qutraj_run, only : rho_return_sparse
      use qutraj_run, only : sol
      use qutraj_run, only : csr_val
      use qutraj_run, only : csr_col
      use qutraj_run, only : csr_ptr
      use qutraj_run, only : csr_nrows
      use qutraj_run, only : csr_ncols
      use qutraj_run, only : col_times
      use qutraj_run, only : col_which
      use qutraj_run, only : psi0_dims1
      use qutraj_run, only : ptrace_sel
      use qutraj_run, only : rho_reduced_dim
      use qutraj_run, only : calc_entropy
      use qutraj_run, only : reduced_state_entropy
      use qutraj_run, only : init_tlist
      use qutraj_run, only : init_psi0
      use qutraj_run, only : init_ptrace_stuff
      use qutraj_run, only : init_hamiltonian
      use qutraj_run, only : init_c_ops
      use qutraj_run, only : init_e_ops
      use qutraj_run, only : init_result
      use qutraj_run, only : get_rho_sparse
      use qutraj_run, only : get_collapses
      use qutraj_run, only : evolve
      use qutraj_run, only : finalize_work
      use qutraj_run, only : finalize_sol
      use qutraj_run, only : test_real_precision
      external f2pysetupfunc
      external f2py_qutraj_run_getdims_tlist
      external f2py_qutraj_run_getdims_psi0
      external f2py_qutraj_run_getdims_sol
      external f2py_qutraj_run_getdims_csr_val
      external f2py_qutraj_run_getdims_csr_col
      external f2py_qutraj_run_getdims_csr_ptr
      external f2py_qutraj_run_getdims_col_times
      external f2py_qutraj_run_getdims_col_which
      external f2py_qutraj_run_getdims_psi0_dims1
      external f2py_qutraj_run_getdims_ptrace_sel
      external f2py_qutraj_run_getdims_reduced_state_entropy
      call f2pysetupfunc(ntraj,n_e_ops,n_c_ops,unravel_type,average_stat&
     &es,average_expect,f2py_qutraj_run_getdims_tlist,order,nsteps,first&
     &_step,min_step,max_step,f2py_qutraj_run_getdims_psi0,rho_return_sp&
     &arse,f2py_qutraj_run_getdims_sol,f2py_qutraj_run_getdims_csr_val,f&
     &2py_qutraj_run_getdims_csr_col,f2py_qutraj_run_getdims_csr_ptr,csr&
     &_nrows,csr_ncols,f2py_qutraj_run_getdims_col_times,f2py_qutraj_run&
     &_getdims_col_which,f2py_qutraj_run_getdims_psi0_dims1,f2py_qutraj_&
     &run_getdims_ptrace_sel,rho_reduced_dim,calc_entropy,f2py_qutraj_ru&
     &n_getdims_reduced_state_entropy,init_tlist,init_psi0,init_ptrace_s&
     &tuff,init_hamiltonian,init_c_ops,init_e_ops,init_result,get_rho_sp&
     &arse,get_collapses,evolve,finalize_work,finalize_sol,test_real_pre&
     &cision)
      end subroutine f2pyinitqutraj_run


